#ifndef jsonHEADER_H
#define jsonHEADER_H 1
#define jsonIN_HEADER 1

#line 5 "C:\\Users\\carlo\\Documents\\Escritorio\\BisonFlexMultipleParsers\\both\\json.lex.h"

#line 7 "C:\\Users\\carlo\\Documents\\Escritorio\\BisonFlexMultipleParsers\\both\\json.lex.h"

#define  JSON_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define JSON_FLEX_MAJOR_VERSION 2
#define JSON_FLEX_MINOR_VERSION 6
#define JSON_FLEX_SUBMINOR_VERSION 4
#if JSON_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef jsonget_lval
#define jsonget_lval_ALREADY_DEFINED
#else
#define jsonget_lval jsonget_lval
#endif

#ifdef jsonset_lval
#define jsonset_lval_ALREADY_DEFINED
#else
#define jsonset_lval jsonset_lval
#endif

#ifdef jsonget_lloc
#define jsonget_lloc_ALREADY_DEFINED
#else
#define jsonget_lloc jsonget_lloc
#endif

#ifdef jsonset_lloc
#define jsonset_lloc_ALREADY_DEFINED
#else
#define jsonset_lloc jsonset_lloc
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define jsonconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define jsonnoreturn __attribute__((__noreturn__))
#else
#define jsonnoreturn
#endif

/* An opaque pointer. */
#ifndef JSON_TYPEDEF_JSON_SCANNER_T
#define JSON_TYPEDEF_JSON_SCANNER_T
typedef void* jsonscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define jsonin jsong->jsonin_r
#define jsonout jsong->jsonout_r
#define jsonextra jsong->jsonextra_r
#define jsonleng jsong->jsonleng_r
#define jsontext jsong->jsontext_r
#define jsonlineno (JSON_CURRENT_BUFFER_LVALUE->json_bs_lineno)
#define jsoncolumn (JSON_CURRENT_BUFFER_LVALUE->json_bs_column)
#define json_flex_debug jsong->json_flex_debug_r

/* Size of default input buffer. */
#ifndef JSON_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, JSON_BUF_SIZE is 2*JSON_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define JSON_BUF_SIZE 32768
#else
#define JSON_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

#ifndef JSON_TYPEDEF_JSON_BUFFER_STATE
#define JSON_TYPEDEF_JSON_BUFFER_STATE
typedef struct json_buffer_state *JSON_BUFFER_STATE;
#endif

#ifndef JSON_TYPEDEF_JSON_SIZE_T
#define JSON_TYPEDEF_JSON_SIZE_T
typedef size_t json_size_t;
#endif

#ifndef JSON_STRUCT_JSON_BUFFER_STATE
#define JSON_STRUCT_JSON_BUFFER_STATE
struct json_buffer_state
	{
	FILE *json_input_file;

	char *json_ch_buf;		/* input buffer */
	char *json_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int json_buf_size;

	/* Number of characters read into json_ch_buf, not including EOB
	 * characters.
	 */
	int json_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int json_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int json_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int json_at_bol;

    int json_bs_lineno; /**< The line count. */
    int json_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int json_fill_buffer;

	int json_buffer_status;

	};
#endif /* !JSON_STRUCT_JSON_BUFFER_STATE */

void jsonrestart ( FILE *input_file , jsonscan_t jsonscanner );
void json_switch_to_buffer ( JSON_BUFFER_STATE new_buffer , jsonscan_t jsonscanner );
JSON_BUFFER_STATE json_create_buffer ( FILE *file, int size , jsonscan_t jsonscanner );
void json_delete_buffer ( JSON_BUFFER_STATE b , jsonscan_t jsonscanner );
void json_flush_buffer ( JSON_BUFFER_STATE b , jsonscan_t jsonscanner );
void jsonpush_buffer_state ( JSON_BUFFER_STATE new_buffer , jsonscan_t jsonscanner );
void jsonpop_buffer_state ( jsonscan_t jsonscanner );

JSON_BUFFER_STATE json_scan_buffer ( char *base, json_size_t size , jsonscan_t jsonscanner );
JSON_BUFFER_STATE json_scan_string ( const char *json_str , jsonscan_t jsonscanner );
JSON_BUFFER_STATE json_scan_bytes ( const char *bytes, int len , jsonscan_t jsonscanner );

void *jsonalloc ( json_size_t , jsonscan_t jsonscanner );
void *jsonrealloc ( void *, json_size_t , jsonscan_t jsonscanner );
void jsonfree ( void * , jsonscan_t jsonscanner );

/* Begin user sect3 */

#define jsonwrap(jsonscanner) (/*CONSTCOND*/1)
#define JSON_SKIP_JSONWRAP

#define jsontext_ptr jsontext_r

#ifdef JSON_HEADER_EXPORT_START_CONDITIONS
#define INITIAL 0

#endif

#ifndef JSON_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef JSON_EXTRA_TYPE
#define JSON_EXTRA_TYPE void *
#endif

int jsonlex_init (jsonscan_t* scanner);

int jsonlex_init_extra ( JSON_EXTRA_TYPE user_defined, jsonscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int jsonlex_destroy ( jsonscan_t jsonscanner );

int jsonget_debug ( jsonscan_t jsonscanner );

void jsonset_debug ( int debug_flag , jsonscan_t jsonscanner );

JSON_EXTRA_TYPE jsonget_extra ( jsonscan_t jsonscanner );

void jsonset_extra ( JSON_EXTRA_TYPE user_defined , jsonscan_t jsonscanner );

FILE *jsonget_in ( jsonscan_t jsonscanner );

void jsonset_in  ( FILE * _in_str , jsonscan_t jsonscanner );

FILE *jsonget_out ( jsonscan_t jsonscanner );

void jsonset_out  ( FILE * _out_str , jsonscan_t jsonscanner );

			int jsonget_leng ( jsonscan_t jsonscanner );

char *jsonget_text ( jsonscan_t jsonscanner );

int jsonget_lineno ( jsonscan_t jsonscanner );

void jsonset_lineno ( int _line_number , jsonscan_t jsonscanner );

int jsonget_column  ( jsonscan_t jsonscanner );

void jsonset_column ( int _column_no , jsonscan_t jsonscanner );

JSONSTYPE * jsonget_lval ( jsonscan_t jsonscanner );

void jsonset_lval ( JSONSTYPE * jsonlval_param , jsonscan_t jsonscanner );

       JSONLTYPE *jsonget_lloc ( jsonscan_t jsonscanner );
    
        void jsonset_lloc ( JSONLTYPE * jsonlloc_param , jsonscan_t jsonscanner );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef JSON_SKIP_JSONWRAP
#ifdef __cplusplus
extern "C" int jsonwrap ( jsonscan_t jsonscanner );
#else
extern int jsonwrap ( jsonscan_t jsonscanner );
#endif
#endif

#ifndef jsontext_ptr
static void json_flex_strncpy ( char *, const char *, int , jsonscan_t jsonscanner);
#endif

#ifdef JSON_NEED_STRLEN
static int json_flex_strlen ( const char * , jsonscan_t jsonscanner);
#endif

#ifndef JSON_NO_INPUT

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef JSON_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define JSON_READ_BUF_SIZE 16384
#else
#define JSON_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef JSON_START_STACK_INCR
#define JSON_START_STACK_INCR 25
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef JSON_DECL
#define JSON_DECL_IS_OURS 1

extern int jsonlex \
               (JSONSTYPE * jsonlval_param, JSONLTYPE * jsonlloc_param , jsonscan_t jsonscanner);

#define JSON_DECL int jsonlex \
               (JSONSTYPE * jsonlval_param, JSONLTYPE * jsonlloc_param , jsonscan_t jsonscanner)
#endif /* !JSON_DECL */

/* json_get_previous_state - get the state just before the EOB char was reached */

#undef JSON_NEW_FILE
#undef JSON_FLUSH_BUFFER
#undef json_set_bol
#undef json_new_buffer
#undef json_set_interactive
#undef JSON_DO_BEFORE_ACTION

#ifdef JSON_DECL_IS_OURS
#undef JSON_DECL_IS_OURS
#undef JSON_DECL
#endif

#ifndef json_create_buffer_ALREADY_DEFINED
#undef json_create_buffer
#endif
#ifndef json_delete_buffer_ALREADY_DEFINED
#undef json_delete_buffer
#endif
#ifndef json_scan_buffer_ALREADY_DEFINED
#undef json_scan_buffer
#endif
#ifndef json_scan_string_ALREADY_DEFINED
#undef json_scan_string
#endif
#ifndef json_scan_bytes_ALREADY_DEFINED
#undef json_scan_bytes
#endif
#ifndef json_init_buffer_ALREADY_DEFINED
#undef json_init_buffer
#endif
#ifndef json_flush_buffer_ALREADY_DEFINED
#undef json_flush_buffer
#endif
#ifndef json_load_buffer_state_ALREADY_DEFINED
#undef json_load_buffer_state
#endif
#ifndef json_switch_to_buffer_ALREADY_DEFINED
#undef json_switch_to_buffer
#endif
#ifndef jsonpush_buffer_state_ALREADY_DEFINED
#undef jsonpush_buffer_state
#endif
#ifndef jsonpop_buffer_state_ALREADY_DEFINED
#undef jsonpop_buffer_state
#endif
#ifndef jsonensure_buffer_stack_ALREADY_DEFINED
#undef jsonensure_buffer_stack
#endif
#ifndef jsonlex_ALREADY_DEFINED
#undef jsonlex
#endif
#ifndef jsonrestart_ALREADY_DEFINED
#undef jsonrestart
#endif
#ifndef jsonlex_init_ALREADY_DEFINED
#undef jsonlex_init
#endif
#ifndef jsonlex_init_extra_ALREADY_DEFINED
#undef jsonlex_init_extra
#endif
#ifndef jsonlex_destroy_ALREADY_DEFINED
#undef jsonlex_destroy
#endif
#ifndef jsonget_debug_ALREADY_DEFINED
#undef jsonget_debug
#endif
#ifndef jsonset_debug_ALREADY_DEFINED
#undef jsonset_debug
#endif
#ifndef jsonget_extra_ALREADY_DEFINED
#undef jsonget_extra
#endif
#ifndef jsonset_extra_ALREADY_DEFINED
#undef jsonset_extra
#endif
#ifndef jsonget_in_ALREADY_DEFINED
#undef jsonget_in
#endif
#ifndef jsonset_in_ALREADY_DEFINED
#undef jsonset_in
#endif
#ifndef jsonget_out_ALREADY_DEFINED
#undef jsonget_out
#endif
#ifndef jsonset_out_ALREADY_DEFINED
#undef jsonset_out
#endif
#ifndef jsonget_leng_ALREADY_DEFINED
#undef jsonget_leng
#endif
#ifndef jsonget_text_ALREADY_DEFINED
#undef jsonget_text
#endif
#ifndef jsonget_lineno_ALREADY_DEFINED
#undef jsonget_lineno
#endif
#ifndef jsonset_lineno_ALREADY_DEFINED
#undef jsonset_lineno
#endif
#ifndef jsonget_column_ALREADY_DEFINED
#undef jsonget_column
#endif
#ifndef jsonset_column_ALREADY_DEFINED
#undef jsonset_column
#endif
#ifndef jsonwrap_ALREADY_DEFINED
#undef jsonwrap
#endif
#ifndef jsonget_lval_ALREADY_DEFINED
#undef jsonget_lval
#endif
#ifndef jsonset_lval_ALREADY_DEFINED
#undef jsonset_lval
#endif
#ifndef jsonget_lloc_ALREADY_DEFINED
#undef jsonget_lloc
#endif
#ifndef jsonset_lloc_ALREADY_DEFINED
#undef jsonset_lloc
#endif
#ifndef jsonalloc_ALREADY_DEFINED
#undef jsonalloc
#endif
#ifndef jsonrealloc_ALREADY_DEFINED
#undef jsonrealloc
#endif
#ifndef jsonfree_ALREADY_DEFINED
#undef jsonfree
#endif
#ifndef jsontext_ALREADY_DEFINED
#undef jsontext
#endif
#ifndef jsonleng_ALREADY_DEFINED
#undef jsonleng
#endif
#ifndef jsonin_ALREADY_DEFINED
#undef jsonin
#endif
#ifndef jsonout_ALREADY_DEFINED
#undef jsonout
#endif
#ifndef json_flex_debug_ALREADY_DEFINED
#undef json_flex_debug
#endif
#ifndef jsonlineno_ALREADY_DEFINED
#undef jsonlineno
#endif
#ifndef jsontables_fload_ALREADY_DEFINED
#undef jsontables_fload
#endif
#ifndef jsontables_destroy_ALREADY_DEFINED
#undef jsontables_destroy
#endif
#ifndef jsonTABLES_NAME_ALREADY_DEFINED
#undef jsonTABLES_NAME
#endif

#line 54 "../json/json.l"


#line 524 "C:\\Users\\carlo\\Documents\\Escritorio\\BisonFlexMultipleParsers\\both\\json.lex.h"
#undef jsonIN_HEADER
#endif /* jsonHEADER_H */
