#line 1 "C:\\Users\\carlo\\Documents\\Escritorio\\BisonFlexMultipleParsers\\both\\json.lex.c"

#line 3 "C:\\Users\\carlo\\Documents\\Escritorio\\BisonFlexMultipleParsers\\both\\json.lex.c"

#define  JSON_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define JSON_FLEX_MAJOR_VERSION 2
#define JSON_FLEX_MINOR_VERSION 6
#define JSON_FLEX_SUBMINOR_VERSION 4
#if JSON_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef jsonget_lval
#define jsonget_lval_ALREADY_DEFINED
#else
#define jsonget_lval jsonget_lval
#endif

#ifdef jsonset_lval
#define jsonset_lval_ALREADY_DEFINED
#else
#define jsonset_lval jsonset_lval
#endif

#ifdef jsonget_lloc
#define jsonget_lloc_ALREADY_DEFINED
#else
#define jsonget_lloc jsonget_lloc
#endif

#ifdef jsonset_lloc
#define jsonset_lloc_ALREADY_DEFINED
#else
#define jsonset_lloc jsonset_lloc
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define jsonconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define jsonnoreturn __attribute__((__noreturn__))
#else
#define jsonnoreturn
#endif

/* Returned upon end-of-file. */
#define JSON_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define JSON_SC_TO_UI(c) ((JSON_CHAR) (c))

/* An opaque pointer. */
#ifndef JSON_TYPEDEF_JSON_SCANNER_T
#define JSON_TYPEDEF_JSON_SCANNER_T
typedef void* jsonscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define jsonin jsong->jsonin_r
#define jsonout jsong->jsonout_r
#define jsonextra jsong->jsonextra_r
#define jsonleng jsong->jsonleng_r
#define jsontext jsong->jsontext_r
#define jsonlineno (JSON_CURRENT_BUFFER_LVALUE->json_bs_lineno)
#define jsoncolumn (JSON_CURRENT_BUFFER_LVALUE->json_bs_column)
#define json_flex_debug jsong->json_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN jsong->json_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The JSONSTATE alias is for lex
 * compatibility.
 */
#define JSON_START ((jsong->json_start - 1) / 2)
#define JSONSTATE JSON_START
/* Action number for EOF rule of a given start state. */
#define JSON_STATE_EOF(state) (JSON_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define JSON_NEW_FILE jsonrestart( jsonin , jsonscanner )
#define JSON_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef JSON_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, JSON_BUF_SIZE is 2*JSON_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define JSON_BUF_SIZE 32768
#else
#define JSON_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define JSON_STATE_BUF_SIZE   ((JSON_BUF_SIZE + 2) * sizeof(json_state_type))

#ifndef JSON_TYPEDEF_JSON_BUFFER_STATE
#define JSON_TYPEDEF_JSON_BUFFER_STATE
typedef struct json_buffer_state *JSON_BUFFER_STATE;
#endif

#ifndef JSON_TYPEDEF_JSON_SIZE_T
#define JSON_TYPEDEF_JSON_SIZE_T
typedef size_t json_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for json_rule_can_match_eol because it requires
     *       access to the local variable json_act. Since jsonless() is a macro, it would break
     *       existing scanners that call jsonless() from OUTSIDE jsonlex.
     *       One obvious solution it to make json_act a global. I tried that, and saw
     *       a 5% performance hit in a non-jsonlineno scanner, because json_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  JSON_LESS_LINENO(n) \
            do { \
                int jsonl;\
                for ( jsonl = n; jsonl < jsonleng; ++jsonl )\
                    if ( jsontext[jsonl] == '\n' )\
                        --jsonlineno;\
            }while(0)
    #define JSON_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = json_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --jsonlineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define jsonless(n) \
	do \
		{ \
		/* Undo effects of setting up jsontext. */ \
        int jsonless_macro_arg = (n); \
        JSON_LESS_LINENO(jsonless_macro_arg);\
		*json_cp = jsong->json_hold_char; \
		JSON_RESTORE_JSON_MORE_OFFSET \
		jsong->json_c_buf_p = json_cp = json_bp + jsonless_macro_arg - JSON_MORE_ADJ; \
		JSON_DO_BEFORE_ACTION; /* set up jsontext again */ \
		} \
	while ( 0 )
#define unput(c) jsonunput( c, jsong->jsontext_ptr , jsonscanner )

#ifndef JSON_STRUCT_JSON_BUFFER_STATE
#define JSON_STRUCT_JSON_BUFFER_STATE
struct json_buffer_state
	{
	FILE *json_input_file;

	char *json_ch_buf;		/* input buffer */
	char *json_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int json_buf_size;

	/* Number of characters read into json_ch_buf, not including EOB
	 * characters.
	 */
	int json_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int json_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int json_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int json_at_bol;

    int json_bs_lineno; /**< The line count. */
    int json_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int json_fill_buffer;

	int json_buffer_status;

#define JSON_BUFFER_NEW 0
#define JSON_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as JSON_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via jsonrestart()), so that the user can continue scanning by
	 * just pointing jsonin at a new input file.
	 */
#define JSON_BUFFER_EOF_PENDING 2

	};
#endif /* !JSON_STRUCT_JSON_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define JSON_CURRENT_BUFFER ( jsong->json_buffer_stack \
                          ? jsong->json_buffer_stack[jsong->json_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define JSON_CURRENT_BUFFER_LVALUE jsong->json_buffer_stack[jsong->json_buffer_stack_top]

void jsonrestart ( FILE *input_file , jsonscan_t jsonscanner );
void json_switch_to_buffer ( JSON_BUFFER_STATE new_buffer , jsonscan_t jsonscanner );
JSON_BUFFER_STATE json_create_buffer ( FILE *file, int size , jsonscan_t jsonscanner );
void json_delete_buffer ( JSON_BUFFER_STATE b , jsonscan_t jsonscanner );
void json_flush_buffer ( JSON_BUFFER_STATE b , jsonscan_t jsonscanner );
void jsonpush_buffer_state ( JSON_BUFFER_STATE new_buffer , jsonscan_t jsonscanner );
void jsonpop_buffer_state ( jsonscan_t jsonscanner );

static void jsonensure_buffer_stack ( jsonscan_t jsonscanner );
static void json_load_buffer_state ( jsonscan_t jsonscanner );
static void json_init_buffer ( JSON_BUFFER_STATE b, FILE *file , jsonscan_t jsonscanner );
#define JSON_FLUSH_BUFFER json_flush_buffer( JSON_CURRENT_BUFFER , jsonscanner)

JSON_BUFFER_STATE json_scan_buffer ( char *base, json_size_t size , jsonscan_t jsonscanner );
JSON_BUFFER_STATE json_scan_string ( const char *json_str , jsonscan_t jsonscanner );
JSON_BUFFER_STATE json_scan_bytes ( const char *bytes, int len , jsonscan_t jsonscanner );

void *jsonalloc ( json_size_t , jsonscan_t jsonscanner );
void *jsonrealloc ( void *, json_size_t , jsonscan_t jsonscanner );
void jsonfree ( void * , jsonscan_t jsonscanner );

#define json_new_buffer json_create_buffer
#define json_set_interactive(is_interactive) \
	{ \
	if ( ! JSON_CURRENT_BUFFER ){ \
        jsonensure_buffer_stack (jsonscanner); \
		JSON_CURRENT_BUFFER_LVALUE =    \
            json_create_buffer( jsonin, JSON_BUF_SIZE , jsonscanner); \
	} \
	JSON_CURRENT_BUFFER_LVALUE->json_is_interactive = is_interactive; \
	}
#define json_set_bol(at_bol) \
	{ \
	if ( ! JSON_CURRENT_BUFFER ){\
        jsonensure_buffer_stack (jsonscanner); \
		JSON_CURRENT_BUFFER_LVALUE =    \
            json_create_buffer( jsonin, JSON_BUF_SIZE , jsonscanner); \
	} \
	JSON_CURRENT_BUFFER_LVALUE->json_at_bol = at_bol; \
	}
#define JSON_AT_BOL() (JSON_CURRENT_BUFFER_LVALUE->json_at_bol)

/* Begin user sect3 */

#define jsonwrap(jsonscanner) (/*CONSTCOND*/1)
#define JSON_SKIP_JSONWRAP
typedef flex_uint8_t JSON_CHAR;

typedef int json_state_type;

#define jsontext_ptr jsontext_r

static json_state_type json_get_previous_state ( jsonscan_t jsonscanner );
static json_state_type json_try_NUL_trans ( json_state_type current_state  , jsonscan_t jsonscanner);
static int json_get_next_buffer ( jsonscan_t jsonscanner );
static void jsonnoreturn json_fatal_error ( const char* msg , jsonscan_t jsonscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up jsontext.
 */
#define JSON_DO_BEFORE_ACTION \
	jsong->jsontext_ptr = json_bp; \
	jsonleng = (int) (json_cp - json_bp); \
	jsong->json_hold_char = *json_cp; \
	*json_cp = '\0'; \
	jsong->json_c_buf_p = json_cp;
#define JSON_NUM_RULES 14
#define JSON_END_OF_BUFFER 15
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct json_trans_info
	{
	flex_int32_t json_verify;
	flex_int32_t json_nxt;
	};
static const flex_int16_t json_accept[46] =
    {   0,
        0,    0,   15,   13,   12,   13,    1,   13,   11,   11,
        2,    6,    7,   13,   13,   13,    8,    9,   12,    0,
       10,    0,   11,   11,    0,    0,   11,    0,    0,    0,
        0,   11,    0,   11,    0,    0,    0,    0,    0,    5,
        3,    0,    4,    0,    0
    } ;

static const JSON_CHAR json_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    6,    7,    8,    9,   10,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   12,    1,    1,
        1,    1,    1,    1,   13,   13,   13,   13,   14,   13,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       15,   16,   17,    1,    1,    1,   18,   19,   13,   13,

       20,   21,    1,    1,    1,    1,    1,   22,    1,   23,
        1,    1,    1,   24,   25,   26,   27,    1,    1,    1,
        1,    1,   28,    1,   29,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const JSON_CHAR json_meta[30] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        2,    1,    2,    2,    1,    1,    1,    2,    2,    2,
        2,    1,    1,    1,    1,    1,    1,    1,    1
    } ;

static const flex_int16_t json_base[51] =
    {   0,
        0,    0,   90,   91,   28,   28,   91,   23,   27,   40,
       91,   91,   91,   71,   61,   63,   91,   91,   34,   36,
       91,   57,   35,    0,   28,   52,    0,   60,   57,   50,
        0,   54,   35,   59,   50,   50,   51,    0,   47,   91,
       91,    0,   91,    0,   91,   84,   56,   54,   51,   40
    } ;

static const flex_int16_t json_def[51] =
    {   0,
       45,    1,   45,   45,   45,   46,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   46,
       45,   45,   45,   10,   45,   45,   10,   45,   45,   45,
       47,   45,   45,   45,   45,   45,   45,   48,   45,   45,
       45,   49,   45,   50,    0,   45,   45,   45,   45,   45
    } ;

static const flex_int16_t json_nxt[121] =
    {   0,
        4,    5,    5,    6,    4,    7,    8,    4,    4,    9,
       10,   11,    4,    4,   12,    4,   13,    4,    4,    4,
       14,    4,   15,    4,    4,   16,    4,   17,   18,   19,
       19,   21,   23,   24,   25,   19,   19,   32,   32,   21,
       26,   20,   25,   22,   34,   34,   26,   25,   26,   27,
       27,   22,   44,   26,   26,   42,   33,   38,   33,   26,
       20,   34,   34,   32,   32,   20,   43,   26,   34,   34,
       41,   40,   20,   26,   39,   20,   37,   20,   36,   20,
       20,   35,   20,   31,   20,   20,   30,   29,   28,   45,
        3,   45,   45,   45,   45,   45,   45,   45,   45,   45,

       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45
    } ;

static const flex_int16_t json_chk[121] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    5,
        5,    6,    8,    8,    9,   19,   19,   25,   25,   20,
        9,   50,   23,    6,   33,   33,    9,   10,   23,   10,
       10,   20,   49,   10,   23,   48,   26,   47,   26,   10,
       22,   26,   26,   32,   32,   22,   39,   32,   34,   34,
       37,   36,   22,   32,   35,   22,   30,   22,   29,   22,
       22,   28,   22,   22,   46,   46,   16,   15,   14,    3,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,

       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t json_rule_can_match_eol[15] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,     };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define jsonmore() jsonmore_used_but_not_detected
#define JSON_MORE_ADJ 0
#define JSON_RESTORE_JSON_MORE_OFFSET
#line 1 "../json/json.l"
#define JSON_NO_INPUT 1
#line 6 "../json/json.l"
	#include <stdlib.h> 
	#include <string.h>
	#include "json.tab.h" 
	
	#define JSON_USER_ACTION                                             \
	jsonlloc->first_line = jsonlloc->last_line;                            \
	jsonlloc->first_column = jsonlloc->last_column;                        \
	if (jsonlloc->last_line == jsonlineno)                                 \
		jsonlloc->last_column += jsonleng;                                 \
	else {                                                             \
		jsonlloc->last_line = jsonlineno;                                  \
		jsonlloc->last_column = jsontext + jsonleng - strrchr(jsontext, '\n'); \
	}
#line 522 "C:\\Users\\carlo\\Documents\\Escritorio\\BisonFlexMultipleParsers\\both\\json.lex.c"
#line 523 "C:\\Users\\carlo\\Documents\\Escritorio\\BisonFlexMultipleParsers\\both\\json.lex.c"

#define INITIAL 0

#ifndef JSON_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef JSON_EXTRA_TYPE
#define JSON_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct jsonguts_t
    {

    /* User-defined. Not touched by flex. */
    JSON_EXTRA_TYPE jsonextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *jsonin_r, *jsonout_r;
    size_t json_buffer_stack_top; /**< index of top of stack. */
    size_t json_buffer_stack_max; /**< capacity of stack. */
    JSON_BUFFER_STATE * json_buffer_stack; /**< Stack as an array. */
    char json_hold_char;
    int json_n_chars;
    int jsonleng_r;
    char *json_c_buf_p;
    int json_init;
    int json_start;
    int json_did_buffer_switch_on_eof;
    int json_start_stack_ptr;
    int json_start_stack_depth;
    int *json_start_stack;
    json_state_type json_last_accepting_state;
    char* json_last_accepting_cpos;

    int jsonlineno_r;
    int json_flex_debug_r;

    char *jsontext_r;
    int json_more_flag;
    int json_more_len;

    JSONSTYPE * jsonlval_r;

    JSONLTYPE * jsonlloc_r;

    }; /* end struct jsonguts_t */

static int json_init_globals ( jsonscan_t jsonscanner );

    /* This must go here because JSONSTYPE and JSONLTYPE are included
     * from bison output in section 1.*/
    #    define jsonlval jsong->jsonlval_r
    
    #    define jsonlloc jsong->jsonlloc_r
    
int jsonlex_init (jsonscan_t* scanner);

int jsonlex_init_extra ( JSON_EXTRA_TYPE user_defined, jsonscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int jsonlex_destroy ( jsonscan_t jsonscanner );

int jsonget_debug ( jsonscan_t jsonscanner );

void jsonset_debug ( int debug_flag , jsonscan_t jsonscanner );

JSON_EXTRA_TYPE jsonget_extra ( jsonscan_t jsonscanner );

void jsonset_extra ( JSON_EXTRA_TYPE user_defined , jsonscan_t jsonscanner );

FILE *jsonget_in ( jsonscan_t jsonscanner );

void jsonset_in  ( FILE * _in_str , jsonscan_t jsonscanner );

FILE *jsonget_out ( jsonscan_t jsonscanner );

void jsonset_out  ( FILE * _out_str , jsonscan_t jsonscanner );

			int jsonget_leng ( jsonscan_t jsonscanner );

char *jsonget_text ( jsonscan_t jsonscanner );

int jsonget_lineno ( jsonscan_t jsonscanner );

void jsonset_lineno ( int _line_number , jsonscan_t jsonscanner );

int jsonget_column  ( jsonscan_t jsonscanner );

void jsonset_column ( int _column_no , jsonscan_t jsonscanner );

JSONSTYPE * jsonget_lval ( jsonscan_t jsonscanner );

void jsonset_lval ( JSONSTYPE * jsonlval_param , jsonscan_t jsonscanner );

       JSONLTYPE *jsonget_lloc ( jsonscan_t jsonscanner );
    
        void jsonset_lloc ( JSONLTYPE * jsonlloc_param , jsonscan_t jsonscanner );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef JSON_SKIP_JSONWRAP
#ifdef __cplusplus
extern "C" int jsonwrap ( jsonscan_t jsonscanner );
#else
extern int jsonwrap ( jsonscan_t jsonscanner );
#endif
#endif

#ifndef JSON_NO_UNPUT
    
#endif

#ifndef jsontext_ptr
static void json_flex_strncpy ( char *, const char *, int , jsonscan_t jsonscanner);
#endif

#ifdef JSON_NEED_STRLEN
static int json_flex_strlen ( const char * , jsonscan_t jsonscanner);
#endif

#ifndef JSON_NO_INPUT
#ifdef __cplusplus
static int jsoninput ( jsonscan_t jsonscanner );
#else
static int input ( jsonscan_t jsonscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef JSON_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define JSON_READ_BUF_SIZE 16384
#else
#define JSON_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( jsontext, (size_t) jsonleng, 1, jsonout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or JSON_NULL,
 * is returned in "result".
 */
#ifndef JSON_INPUT
#define JSON_INPUT(buf,result,max_size) \
	if ( JSON_CURRENT_BUFFER_LVALUE->json_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( jsonin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( jsonin ) ) \
			JSON_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (json_size_t) max_size, jsonin)) == 0 && ferror(jsonin)) \
			{ \
			if( errno != EINTR) \
				{ \
				JSON_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(jsonin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "jsonterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef jsonterminate
#define jsonterminate() return JSON_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef JSON_START_STACK_INCR
#define JSON_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef JSON_FATAL_ERROR
#define JSON_FATAL_ERROR(msg) json_fatal_error( msg , jsonscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef JSON_DECL
#define JSON_DECL_IS_OURS 1

extern int jsonlex \
               (JSONSTYPE * jsonlval_param, JSONLTYPE * jsonlloc_param , jsonscan_t jsonscanner);

#define JSON_DECL int jsonlex \
               (JSONSTYPE * jsonlval_param, JSONLTYPE * jsonlloc_param , jsonscan_t jsonscanner)
#endif /* !JSON_DECL */

/* Code executed at the beginning of each rule, after jsontext and jsonleng
 * have been set up.
 */
#ifndef JSON_USER_ACTION
#define JSON_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef JSON_BREAK
#define JSON_BREAK /*LINTED*/break;
#endif

#define JSON_RULE_SETUP \
	JSON_USER_ACTION

/** The main scanner function which does all the work.
 */
JSON_DECL
{
	json_state_type json_current_state;
	char *json_cp, *json_bp;
	int json_act;
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;

    jsonlval = jsonlval_param;

    jsonlloc = jsonlloc_param;

	if ( !jsong->json_init )
		{
		jsong->json_init = 1;

#ifdef JSON_USER_INIT
		JSON_USER_INIT;
#endif

		if ( ! jsong->json_start )
			jsong->json_start = 1;	/* first start state */

		if ( ! jsonin )
			jsonin = stdin;

		if ( ! jsonout )
			jsonout = stdout;

		if ( ! JSON_CURRENT_BUFFER ) {
			jsonensure_buffer_stack (jsonscanner);
			JSON_CURRENT_BUFFER_LVALUE =
				json_create_buffer( jsonin, JSON_BUF_SIZE , jsonscanner);
		}

		json_load_buffer_state( jsonscanner );
		}

	{
#line 39 "../json/json.l"

#line 807 "C:\\Users\\carlo\\Documents\\Escritorio\\BisonFlexMultipleParsers\\both\\json.lex.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		json_cp = jsong->json_c_buf_p;

		/* Support of jsontext. */
		*json_cp = jsong->json_hold_char;

		/* json_bp points to the position in json_ch_buf of the start of
		 * the current run.
		 */
		json_bp = json_cp;

		json_current_state = jsong->json_start;
json_match:
		do
			{
			JSON_CHAR json_c = json_ec[JSON_SC_TO_UI(*json_cp)] ;
			if ( json_accept[json_current_state] )
				{
				jsong->json_last_accepting_state = json_current_state;
				jsong->json_last_accepting_cpos = json_cp;
				}
			while ( json_chk[json_base[json_current_state] + json_c] != json_current_state )
				{
				json_current_state = (int) json_def[json_current_state];
				if ( json_current_state >= 46 )
					json_c = json_meta[json_c];
				}
			json_current_state = json_nxt[json_base[json_current_state] + json_c];
			++json_cp;
			}
		while ( json_base[json_current_state] != 91 );

json_find_action:
		json_act = json_accept[json_current_state];
		if ( json_act == 0 )
			{ /* have to back up */
			json_cp = jsong->json_last_accepting_cpos;
			json_current_state = jsong->json_last_accepting_state;
			json_act = json_accept[json_current_state];
			}

		JSON_DO_BEFORE_ACTION;

		if ( json_act != JSON_END_OF_BUFFER && json_rule_can_match_eol[json_act] )
			{
			int jsonl;
			for ( jsonl = 0; jsonl < jsonleng; ++jsonl )
				if ( jsontext[jsonl] == '\n' )
					
    do{ jsonlineno++;
        jsoncolumn=0;
    }while(0)
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( json_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of JSON_DO_BEFORE_ACTION */
			*json_cp = jsong->json_hold_char;
			json_cp = jsong->json_last_accepting_cpos;
			json_current_state = jsong->json_last_accepting_state;
			goto json_find_action;

case 1:
JSON_RULE_SETUP
#line 40 "../json/json.l"
{printf("Comma\n"); return JSON_TOK_Comma;}
	JSON_BREAK
case 2:
JSON_RULE_SETUP
#line 41 "../json/json.l"
{printf("Semicolon\n"); return JSON_TOK_Semicolon;}
	JSON_BREAK
case 3:
JSON_RULE_SETUP
#line 42 "../json/json.l"
{printf("True\n"); return JSON_TOK_True;}
	JSON_BREAK
case 4:
JSON_RULE_SETUP
#line 43 "../json/json.l"
{printf("False\n"); return JSON_TOK_False;}
	JSON_BREAK
case 5:
JSON_RULE_SETUP
#line 44 "../json/json.l"
{printf("Null\n"); return JSON_TOK_Null;}
	JSON_BREAK
case 6:
JSON_RULE_SETUP
#line 45 "../json/json.l"
{printf("Bracket0\n"); return JSON_TOK_Bracket0;}
	JSON_BREAK
case 7:
JSON_RULE_SETUP
#line 46 "../json/json.l"
{printf("Bracket1\n"); return JSON_TOK_Bracket1;}
	JSON_BREAK
case 8:
JSON_RULE_SETUP
#line 47 "../json/json.l"
{printf("Curly0\n"); return JSON_TOK_Curly0;}
	JSON_BREAK
case 9:
JSON_RULE_SETUP
#line 48 "../json/json.l"
{printf("Curly1\n"); return JSON_TOK_Curly1;}
	JSON_BREAK
case 10:
/* rule 10 can match eol */
JSON_RULE_SETUP
#line 49 "../json/json.l"
{printf("String\n"); return JSON_TOK_String;}
	JSON_BREAK
case 11:
JSON_RULE_SETUP
#line 50 "../json/json.l"
{printf("Number\n"); return JSON_TOK_Number;}
	JSON_BREAK
case 12:
/* rule 12 can match eol */
JSON_RULE_SETUP
#line 51 "../json/json.l"
{printf("Ws\n"); return JSON_TOK_Ws;}
	JSON_BREAK
case 13:
/* rule 13 can match eol */
JSON_RULE_SETUP
#line 52 "../json/json.l"
{printf("Error... Default rule\n");}
	JSON_BREAK
case 14:
JSON_RULE_SETUP
#line 54 "../json/json.l"
JSON_FATAL_ERROR( "flex scanner jammed" );
	JSON_BREAK
#line 949 "C:\\Users\\carlo\\Documents\\Escritorio\\BisonFlexMultipleParsers\\both\\json.lex.c"
case JSON_STATE_EOF(INITIAL):
	jsonterminate();

	case JSON_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int json_amount_of_matched_text = (int) (json_cp - jsong->jsontext_ptr) - 1;

		/* Undo the effects of JSON_DO_BEFORE_ACTION. */
		*json_cp = jsong->json_hold_char;
		JSON_RESTORE_JSON_MORE_OFFSET

		if ( JSON_CURRENT_BUFFER_LVALUE->json_buffer_status == JSON_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed jsonin at a new source and called
			 * jsonlex().  If so, then we have to assure
			 * consistency between JSON_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			jsong->json_n_chars = JSON_CURRENT_BUFFER_LVALUE->json_n_chars;
			JSON_CURRENT_BUFFER_LVALUE->json_input_file = jsonin;
			JSON_CURRENT_BUFFER_LVALUE->json_buffer_status = JSON_BUFFER_NORMAL;
			}

		/* Note that here we test for json_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since json_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( jsong->json_c_buf_p <= &JSON_CURRENT_BUFFER_LVALUE->json_ch_buf[jsong->json_n_chars] )
			{ /* This was really a NUL. */
			json_state_type json_next_state;

			jsong->json_c_buf_p = jsong->jsontext_ptr + json_amount_of_matched_text;

			json_current_state = json_get_previous_state( jsonscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * json_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			json_next_state = json_try_NUL_trans( json_current_state , jsonscanner);

			json_bp = jsong->jsontext_ptr + JSON_MORE_ADJ;

			if ( json_next_state )
				{
				/* Consume the NUL. */
				json_cp = ++jsong->json_c_buf_p;
				json_current_state = json_next_state;
				goto json_match;
				}

			else
				{
				json_cp = jsong->json_c_buf_p;
				goto json_find_action;
				}
			}

		else switch ( json_get_next_buffer( jsonscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				jsong->json_did_buffer_switch_on_eof = 0;

				if ( jsonwrap( jsonscanner ) )
					{
					/* Note: because we've taken care in
					 * json_get_next_buffer() to have set up
					 * jsontext, we can now set up
					 * json_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * JSON_NULL, it'll still work - another
					 * JSON_NULL will get returned.
					 */
					jsong->json_c_buf_p = jsong->jsontext_ptr + JSON_MORE_ADJ;

					json_act = JSON_STATE_EOF(JSON_START);
					goto do_action;
					}

				else
					{
					if ( ! jsong->json_did_buffer_switch_on_eof )
						JSON_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				jsong->json_c_buf_p =
					jsong->jsontext_ptr + json_amount_of_matched_text;

				json_current_state = json_get_previous_state( jsonscanner );

				json_cp = jsong->json_c_buf_p;
				json_bp = jsong->jsontext_ptr + JSON_MORE_ADJ;
				goto json_match;

			case EOB_ACT_LAST_MATCH:
				jsong->json_c_buf_p =
				&JSON_CURRENT_BUFFER_LVALUE->json_ch_buf[jsong->json_n_chars];

				json_current_state = json_get_previous_state( jsonscanner );

				json_cp = jsong->json_c_buf_p;
				json_bp = jsong->jsontext_ptr + JSON_MORE_ADJ;
				goto json_find_action;
			}
		break;
		}

	default:
		JSON_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of jsonlex */

/* json_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int json_get_next_buffer (jsonscan_t jsonscanner)
{
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;
	char *dest = JSON_CURRENT_BUFFER_LVALUE->json_ch_buf;
	char *source = jsong->jsontext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( jsong->json_c_buf_p > &JSON_CURRENT_BUFFER_LVALUE->json_ch_buf[jsong->json_n_chars + 1] )
		JSON_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( JSON_CURRENT_BUFFER_LVALUE->json_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( jsong->json_c_buf_p - jsong->jsontext_ptr - JSON_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (jsong->json_c_buf_p - jsong->jsontext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( JSON_CURRENT_BUFFER_LVALUE->json_buffer_status == JSON_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		JSON_CURRENT_BUFFER_LVALUE->json_n_chars = jsong->json_n_chars = 0;

	else
		{
			int num_to_read =
			JSON_CURRENT_BUFFER_LVALUE->json_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			JSON_BUFFER_STATE b = JSON_CURRENT_BUFFER_LVALUE;

			int json_c_buf_p_offset =
				(int) (jsong->json_c_buf_p - b->json_ch_buf);

			if ( b->json_is_our_buffer )
				{
				int new_size = b->json_buf_size * 2;

				if ( new_size <= 0 )
					b->json_buf_size += b->json_buf_size / 8;
				else
					b->json_buf_size *= 2;

				b->json_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					jsonrealloc( (void *) b->json_ch_buf,
							 (json_size_t) (b->json_buf_size + 2) , jsonscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->json_ch_buf = NULL;

			if ( ! b->json_ch_buf )
				JSON_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			jsong->json_c_buf_p = &b->json_ch_buf[json_c_buf_p_offset];

			num_to_read = JSON_CURRENT_BUFFER_LVALUE->json_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > JSON_READ_BUF_SIZE )
			num_to_read = JSON_READ_BUF_SIZE;

		/* Read in more data. */
		JSON_INPUT( (&JSON_CURRENT_BUFFER_LVALUE->json_ch_buf[number_to_move]),
			jsong->json_n_chars, num_to_read );

		JSON_CURRENT_BUFFER_LVALUE->json_n_chars = jsong->json_n_chars;
		}

	if ( jsong->json_n_chars == 0 )
		{
		if ( number_to_move == JSON_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			jsonrestart( jsonin  , jsonscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			JSON_CURRENT_BUFFER_LVALUE->json_buffer_status =
				JSON_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((jsong->json_n_chars + number_to_move) > JSON_CURRENT_BUFFER_LVALUE->json_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = jsong->json_n_chars + number_to_move + (jsong->json_n_chars >> 1);
		JSON_CURRENT_BUFFER_LVALUE->json_ch_buf = (char *) jsonrealloc(
			(void *) JSON_CURRENT_BUFFER_LVALUE->json_ch_buf, (json_size_t) new_size , jsonscanner );
		if ( ! JSON_CURRENT_BUFFER_LVALUE->json_ch_buf )
			JSON_FATAL_ERROR( "out of dynamic memory in json_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		JSON_CURRENT_BUFFER_LVALUE->json_buf_size = (int) (new_size - 2);
	}

	jsong->json_n_chars += number_to_move;
	JSON_CURRENT_BUFFER_LVALUE->json_ch_buf[jsong->json_n_chars] = JSON_END_OF_BUFFER_CHAR;
	JSON_CURRENT_BUFFER_LVALUE->json_ch_buf[jsong->json_n_chars + 1] = JSON_END_OF_BUFFER_CHAR;

	jsong->jsontext_ptr = &JSON_CURRENT_BUFFER_LVALUE->json_ch_buf[0];

	return ret_val;
}

/* json_get_previous_state - get the state just before the EOB char was reached */

    static json_state_type json_get_previous_state (jsonscan_t jsonscanner)
{
	json_state_type json_current_state;
	char *json_cp;
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;

	json_current_state = jsong->json_start;

	for ( json_cp = jsong->jsontext_ptr + JSON_MORE_ADJ; json_cp < jsong->json_c_buf_p; ++json_cp )
		{
		JSON_CHAR json_c = (*json_cp ? json_ec[JSON_SC_TO_UI(*json_cp)] : 1);
		if ( json_accept[json_current_state] )
			{
			jsong->json_last_accepting_state = json_current_state;
			jsong->json_last_accepting_cpos = json_cp;
			}
		while ( json_chk[json_base[json_current_state] + json_c] != json_current_state )
			{
			json_current_state = (int) json_def[json_current_state];
			if ( json_current_state >= 46 )
				json_c = json_meta[json_c];
			}
		json_current_state = json_nxt[json_base[json_current_state] + json_c];
		}

	return json_current_state;
}

/* json_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = json_try_NUL_trans( current_state );
 */
    static json_state_type json_try_NUL_trans  (json_state_type json_current_state , jsonscan_t jsonscanner)
{
	int json_is_jam;
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner; /* This var may be unused depending upon options. */
	char *json_cp = jsong->json_c_buf_p;

	JSON_CHAR json_c = 1;
	if ( json_accept[json_current_state] )
		{
		jsong->json_last_accepting_state = json_current_state;
		jsong->json_last_accepting_cpos = json_cp;
		}
	while ( json_chk[json_base[json_current_state] + json_c] != json_current_state )
		{
		json_current_state = (int) json_def[json_current_state];
		if ( json_current_state >= 46 )
			json_c = json_meta[json_c];
		}
	json_current_state = json_nxt[json_base[json_current_state] + json_c];
	json_is_jam = (json_current_state == 45);

	(void)jsong;
	return json_is_jam ? 0 : json_current_state;
}

#ifndef JSON_NO_UNPUT

#endif

#ifndef JSON_NO_INPUT
#ifdef __cplusplus
    static int jsoninput (jsonscan_t jsonscanner)
#else
    static int input  (jsonscan_t jsonscanner)
#endif

{
	int c;
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;

	*jsong->json_c_buf_p = jsong->json_hold_char;

	if ( *jsong->json_c_buf_p == JSON_END_OF_BUFFER_CHAR )
		{
		/* json_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( jsong->json_c_buf_p < &JSON_CURRENT_BUFFER_LVALUE->json_ch_buf[jsong->json_n_chars] )
			/* This was really a NUL. */
			*jsong->json_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (jsong->json_c_buf_p - jsong->jsontext_ptr);
			++jsong->json_c_buf_p;

			switch ( json_get_next_buffer( jsonscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because json_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					jsonrestart( jsonin , jsonscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( jsonwrap( jsonscanner ) )
						return 0;

					if ( ! jsong->json_did_buffer_switch_on_eof )
						JSON_NEW_FILE;
#ifdef __cplusplus
					return jsoninput(jsonscanner);
#else
					return input(jsonscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					jsong->json_c_buf_p = jsong->jsontext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) jsong->json_c_buf_p;	/* cast for 8-bit char's */
	*jsong->json_c_buf_p = '\0';	/* preserve jsontext */
	jsong->json_hold_char = *++jsong->json_c_buf_p;

	if ( c == '\n' )
		
    do{ jsonlineno++;
        jsoncolumn=0;
    }while(0)
;

	return c;
}
#endif	/* ifndef JSON_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param jsonscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void jsonrestart  (FILE * input_file , jsonscan_t jsonscanner)
{
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;

	if ( ! JSON_CURRENT_BUFFER ){
        jsonensure_buffer_stack (jsonscanner);
		JSON_CURRENT_BUFFER_LVALUE =
            json_create_buffer( jsonin, JSON_BUF_SIZE , jsonscanner);
	}

	json_init_buffer( JSON_CURRENT_BUFFER, input_file , jsonscanner);
	json_load_buffer_state( jsonscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param jsonscanner The scanner object.
 */
    void json_switch_to_buffer  (JSON_BUFFER_STATE  new_buffer , jsonscan_t jsonscanner)
{
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		jsonpop_buffer_state();
	 *		jsonpush_buffer_state(new_buffer);
     */
	jsonensure_buffer_stack (jsonscanner);
	if ( JSON_CURRENT_BUFFER == new_buffer )
		return;

	if ( JSON_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*jsong->json_c_buf_p = jsong->json_hold_char;
		JSON_CURRENT_BUFFER_LVALUE->json_buf_pos = jsong->json_c_buf_p;
		JSON_CURRENT_BUFFER_LVALUE->json_n_chars = jsong->json_n_chars;
		}

	JSON_CURRENT_BUFFER_LVALUE = new_buffer;
	json_load_buffer_state( jsonscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (jsonwrap()) processing, but the only time this flag
	 * is looked at is after jsonwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	jsong->json_did_buffer_switch_on_eof = 1;
}

static void json_load_buffer_state  (jsonscan_t jsonscanner)
{
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;
	jsong->json_n_chars = JSON_CURRENT_BUFFER_LVALUE->json_n_chars;
	jsong->jsontext_ptr = jsong->json_c_buf_p = JSON_CURRENT_BUFFER_LVALUE->json_buf_pos;
	jsonin = JSON_CURRENT_BUFFER_LVALUE->json_input_file;
	jsong->json_hold_char = *jsong->json_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c JSON_BUF_SIZE.
 * @param jsonscanner The scanner object.
 * @return the allocated buffer state.
 */
    JSON_BUFFER_STATE json_create_buffer  (FILE * file, int  size , jsonscan_t jsonscanner)
{
	JSON_BUFFER_STATE b;
    
	b = (JSON_BUFFER_STATE) jsonalloc( sizeof( struct json_buffer_state ) , jsonscanner );
	if ( ! b )
		JSON_FATAL_ERROR( "out of dynamic memory in json_create_buffer()" );

	b->json_buf_size = size;

	/* json_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->json_ch_buf = (char *) jsonalloc( (json_size_t) (b->json_buf_size + 2) , jsonscanner );
	if ( ! b->json_ch_buf )
		JSON_FATAL_ERROR( "out of dynamic memory in json_create_buffer()" );

	b->json_is_our_buffer = 1;

	json_init_buffer( b, file , jsonscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with json_create_buffer()
 * @param jsonscanner The scanner object.
 */
    void json_delete_buffer (JSON_BUFFER_STATE  b , jsonscan_t jsonscanner)
{
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;

	if ( ! b )
		return;

	if ( b == JSON_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		JSON_CURRENT_BUFFER_LVALUE = (JSON_BUFFER_STATE) 0;

	if ( b->json_is_our_buffer )
		jsonfree( (void *) b->json_ch_buf , jsonscanner );

	jsonfree( (void *) b , jsonscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a jsonrestart() or at EOF.
 */
    static void json_init_buffer  (JSON_BUFFER_STATE  b, FILE * file , jsonscan_t jsonscanner)

{
	int oerrno = errno;
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;

	json_flush_buffer( b , jsonscanner);

	b->json_input_file = file;
	b->json_fill_buffer = 1;

    /* If b is the current buffer, then json_init_buffer was _probably_
     * called from jsonrestart() or through json_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != JSON_CURRENT_BUFFER){
        b->json_bs_lineno = 1;
        b->json_bs_column = 0;
    }

        b->json_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, JSON_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c JSON_CURRENT_BUFFER.
 * @param jsonscanner The scanner object.
 */
    void json_flush_buffer (JSON_BUFFER_STATE  b , jsonscan_t jsonscanner)
{
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;
	if ( ! b )
		return;

	b->json_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->json_ch_buf[0] = JSON_END_OF_BUFFER_CHAR;
	b->json_ch_buf[1] = JSON_END_OF_BUFFER_CHAR;

	b->json_buf_pos = &b->json_ch_buf[0];

	b->json_at_bol = 1;
	b->json_buffer_status = JSON_BUFFER_NEW;

	if ( b == JSON_CURRENT_BUFFER )
		json_load_buffer_state( jsonscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param jsonscanner The scanner object.
 */
void jsonpush_buffer_state (JSON_BUFFER_STATE new_buffer , jsonscan_t jsonscanner)
{
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;
	if (new_buffer == NULL)
		return;

	jsonensure_buffer_stack(jsonscanner);

	/* This block is copied from json_switch_to_buffer. */
	if ( JSON_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*jsong->json_c_buf_p = jsong->json_hold_char;
		JSON_CURRENT_BUFFER_LVALUE->json_buf_pos = jsong->json_c_buf_p;
		JSON_CURRENT_BUFFER_LVALUE->json_n_chars = jsong->json_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (JSON_CURRENT_BUFFER)
		jsong->json_buffer_stack_top++;
	JSON_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from json_switch_to_buffer. */
	json_load_buffer_state( jsonscanner );
	jsong->json_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param jsonscanner The scanner object.
 */
void jsonpop_buffer_state (jsonscan_t jsonscanner)
{
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;
	if (!JSON_CURRENT_BUFFER)
		return;

	json_delete_buffer(JSON_CURRENT_BUFFER , jsonscanner);
	JSON_CURRENT_BUFFER_LVALUE = NULL;
	if (jsong->json_buffer_stack_top > 0)
		--jsong->json_buffer_stack_top;

	if (JSON_CURRENT_BUFFER) {
		json_load_buffer_state( jsonscanner );
		jsong->json_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void jsonensure_buffer_stack (jsonscan_t jsonscanner)
{
	json_size_t num_to_alloc;
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;

	if (!jsong->json_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		jsong->json_buffer_stack = (struct json_buffer_state**)jsonalloc
								(num_to_alloc * sizeof(struct json_buffer_state*)
								, jsonscanner);
		if ( ! jsong->json_buffer_stack )
			JSON_FATAL_ERROR( "out of dynamic memory in jsonensure_buffer_stack()" );

		memset(jsong->json_buffer_stack, 0, num_to_alloc * sizeof(struct json_buffer_state*));

		jsong->json_buffer_stack_max = num_to_alloc;
		jsong->json_buffer_stack_top = 0;
		return;
	}

	if (jsong->json_buffer_stack_top >= (jsong->json_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		json_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = jsong->json_buffer_stack_max + grow_size;
		jsong->json_buffer_stack = (struct json_buffer_state**)jsonrealloc
								(jsong->json_buffer_stack,
								num_to_alloc * sizeof(struct json_buffer_state*)
								, jsonscanner);
		if ( ! jsong->json_buffer_stack )
			JSON_FATAL_ERROR( "out of dynamic memory in jsonensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(jsong->json_buffer_stack + jsong->json_buffer_stack_max, 0, grow_size * sizeof(struct json_buffer_state*));
		jsong->json_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param jsonscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
JSON_BUFFER_STATE json_scan_buffer  (char * base, json_size_t  size , jsonscan_t jsonscanner)
{
	JSON_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != JSON_END_OF_BUFFER_CHAR ||
	     base[size-1] != JSON_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (JSON_BUFFER_STATE) jsonalloc( sizeof( struct json_buffer_state ) , jsonscanner );
	if ( ! b )
		JSON_FATAL_ERROR( "out of dynamic memory in json_scan_buffer()" );

	b->json_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->json_buf_pos = b->json_ch_buf = base;
	b->json_is_our_buffer = 0;
	b->json_input_file = NULL;
	b->json_n_chars = b->json_buf_size;
	b->json_is_interactive = 0;
	b->json_at_bol = 1;
	b->json_fill_buffer = 0;
	b->json_buffer_status = JSON_BUFFER_NEW;

	json_switch_to_buffer( b , jsonscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to jsonlex() will
 * scan from a @e copy of @a str.
 * @param jsonstr a NUL-terminated string to scan
 * @param jsonscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       json_scan_bytes() instead.
 */
JSON_BUFFER_STATE json_scan_string (const char * jsonstr , jsonscan_t jsonscanner)
{
    
	return json_scan_bytes( jsonstr, (int) strlen(jsonstr) , jsonscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to jsonlex() will
 * scan from a @e copy of @a bytes.
 * @param jsonbytes the byte buffer to scan
 * @param _jsonbytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param jsonscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
JSON_BUFFER_STATE json_scan_bytes  (const char * jsonbytes, int  _jsonbytes_len , jsonscan_t jsonscanner)
{
	JSON_BUFFER_STATE b;
	char *buf;
	json_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (json_size_t) (_jsonbytes_len + 2);
	buf = (char *) jsonalloc( n , jsonscanner );
	if ( ! buf )
		JSON_FATAL_ERROR( "out of dynamic memory in json_scan_bytes()" );

	for ( i = 0; i < _jsonbytes_len; ++i )
		buf[i] = jsonbytes[i];

	buf[_jsonbytes_len] = buf[_jsonbytes_len+1] = JSON_END_OF_BUFFER_CHAR;

	b = json_scan_buffer( buf, n , jsonscanner);
	if ( ! b )
		JSON_FATAL_ERROR( "bad buffer in json_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->json_is_our_buffer = 1;

	return b;
}

#ifndef JSON_EXIT_FAILURE
#define JSON_EXIT_FAILURE 2
#endif

static void jsonnoreturn json_fatal_error (const char* msg , jsonscan_t jsonscanner)
{
	struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;
	(void)jsong;
	fprintf( stderr, "%s\n", msg );
	exit( JSON_EXIT_FAILURE );
}

/* Redefine jsonless() so it works in section 3 code. */

#undef jsonless
#define jsonless(n) \
	do \
		{ \
		/* Undo effects of setting up jsontext. */ \
        int jsonless_macro_arg = (n); \
        JSON_LESS_LINENO(jsonless_macro_arg);\
		jsontext[jsonleng] = jsong->json_hold_char; \
		jsong->json_c_buf_p = jsontext + jsonless_macro_arg; \
		jsong->json_hold_char = *jsong->json_c_buf_p; \
		*jsong->json_c_buf_p = '\0'; \
		jsonleng = jsonless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param jsonscanner The scanner object.
 */
JSON_EXTRA_TYPE jsonget_extra  (jsonscan_t jsonscanner)
{
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;
    return jsonextra;
}

/** Get the current line number.
 * @param jsonscanner The scanner object.
 */
int jsonget_lineno  (jsonscan_t jsonscanner)
{
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;

        if (! JSON_CURRENT_BUFFER)
            return 0;
    
    return jsonlineno;
}

/** Get the current column number.
 * @param jsonscanner The scanner object.
 */
int jsonget_column  (jsonscan_t jsonscanner)
{
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;

        if (! JSON_CURRENT_BUFFER)
            return 0;
    
    return jsoncolumn;
}

/** Get the input stream.
 * @param jsonscanner The scanner object.
 */
FILE *jsonget_in  (jsonscan_t jsonscanner)
{
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;
    return jsonin;
}

/** Get the output stream.
 * @param jsonscanner The scanner object.
 */
FILE *jsonget_out  (jsonscan_t jsonscanner)
{
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;
    return jsonout;
}

/** Get the length of the current token.
 * @param jsonscanner The scanner object.
 */
int jsonget_leng  (jsonscan_t jsonscanner)
{
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;
    return jsonleng;
}

/** Get the current token.
 * @param jsonscanner The scanner object.
 */

char *jsonget_text  (jsonscan_t jsonscanner)
{
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;
    return jsontext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param jsonscanner The scanner object.
 */
void jsonset_extra (JSON_EXTRA_TYPE  user_defined , jsonscan_t jsonscanner)
{
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;
    jsonextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param jsonscanner The scanner object.
 */
void jsonset_lineno (int  _line_number , jsonscan_t jsonscanner)
{
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! JSON_CURRENT_BUFFER )
           JSON_FATAL_ERROR( "jsonset_lineno called with no buffer" );
    
    jsonlineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param jsonscanner The scanner object.
 */
void jsonset_column (int  _column_no , jsonscan_t jsonscanner)
{
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;

        /* column is only valid if an input buffer exists. */
        if (! JSON_CURRENT_BUFFER )
           JSON_FATAL_ERROR( "jsonset_column called with no buffer" );
    
    jsoncolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param jsonscanner The scanner object.
 * @see json_switch_to_buffer
 */
void jsonset_in (FILE *  _in_str , jsonscan_t jsonscanner)
{
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;
    jsonin = _in_str ;
}

void jsonset_out (FILE *  _out_str , jsonscan_t jsonscanner)
{
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;
    jsonout = _out_str ;
}

int jsonget_debug  (jsonscan_t jsonscanner)
{
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;
    return json_flex_debug;
}

void jsonset_debug (int  _bdebug , jsonscan_t jsonscanner)
{
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;
    json_flex_debug = _bdebug ;
}

/* Accessor methods for jsonlval and jsonlloc */

JSONSTYPE * jsonget_lval  (jsonscan_t jsonscanner)
{
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;
    return jsonlval;
}

void jsonset_lval (JSONSTYPE *  jsonlval_param , jsonscan_t jsonscanner)
{
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;
    jsonlval = jsonlval_param;
}

JSONLTYPE *jsonget_lloc  (jsonscan_t jsonscanner)
{
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;
    return jsonlloc;
}
    
void jsonset_lloc (JSONLTYPE *  jsonlloc_param , jsonscan_t jsonscanner)
{
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;
    jsonlloc = jsonlloc_param;
}
    
/* User-visible API */

/* jsonlex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int jsonlex_init(jsonscan_t* ptr_json_globals)
{
    if (ptr_json_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_json_globals = (jsonscan_t) jsonalloc ( sizeof( struct jsonguts_t ), NULL );

    if (*ptr_json_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in json_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_json_globals,0x00,sizeof(struct jsonguts_t));

    return json_init_globals ( *ptr_json_globals );
}

/* jsonlex_init_extra has the same functionality as jsonlex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to jsonalloc in
 * the jsonextra field.
 */
int jsonlex_init_extra( JSON_EXTRA_TYPE json_user_defined, jsonscan_t* ptr_json_globals )
{
    struct jsonguts_t dummy_jsonguts;

    jsonset_extra (json_user_defined, &dummy_jsonguts);

    if (ptr_json_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_json_globals = (jsonscan_t) jsonalloc ( sizeof( struct jsonguts_t ), &dummy_jsonguts );

    if (*ptr_json_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    json_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_json_globals,0x00,sizeof(struct jsonguts_t));

    jsonset_extra (json_user_defined, *ptr_json_globals);

    return json_init_globals ( *ptr_json_globals );
}

static int json_init_globals (jsonscan_t jsonscanner)
{
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from jsonlex_destroy(), so don't allocate here.
     */

    jsong->json_buffer_stack = NULL;
    jsong->json_buffer_stack_top = 0;
    jsong->json_buffer_stack_max = 0;
    jsong->json_c_buf_p = NULL;
    jsong->json_init = 0;
    jsong->json_start = 0;

    jsong->json_start_stack_ptr = 0;
    jsong->json_start_stack_depth = 0;
    jsong->json_start_stack =  NULL;

/* Defined in main.c */
#ifdef JSON_STDINIT
    jsonin = stdin;
    jsonout = stdout;
#else
    jsonin = NULL;
    jsonout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * jsonlex_init()
     */
    return 0;
}

/* jsonlex_destroy is for both reentrant and non-reentrant scanners. */
int jsonlex_destroy  (jsonscan_t jsonscanner)
{
    struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;

    /* Pop the buffer stack, destroying each element. */
	while(JSON_CURRENT_BUFFER){
		json_delete_buffer( JSON_CURRENT_BUFFER , jsonscanner );
		JSON_CURRENT_BUFFER_LVALUE = NULL;
		jsonpop_buffer_state(jsonscanner);
	}

	/* Destroy the stack itself. */
	jsonfree(jsong->json_buffer_stack , jsonscanner);
	jsong->json_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        jsonfree( jsong->json_start_stack , jsonscanner );
        jsong->json_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * jsonlex() is called, initialization will occur. */
    json_init_globals( jsonscanner);

    /* Destroy the main struct (reentrant only). */
    jsonfree ( jsonscanner , jsonscanner );
    jsonscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef jsontext_ptr
static void json_flex_strncpy (char* s1, const char * s2, int n , jsonscan_t jsonscanner)
{
	struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;
	(void)jsong;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef JSON_NEED_STRLEN
static int json_flex_strlen (const char * s , jsonscan_t jsonscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *jsonalloc (json_size_t  size , jsonscan_t jsonscanner)
{
	struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;
	(void)jsong;
	return malloc(size);
}

void *jsonrealloc  (void * ptr, json_size_t  size , jsonscan_t jsonscanner)
{
	struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;
	(void)jsong;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void jsonfree (void * ptr , jsonscan_t jsonscanner)
{
	struct jsonguts_t * jsong = (struct jsonguts_t*)jsonscanner;
	(void)jsong;
	free( (char *) ptr );	/* see jsonrealloc() for (char *) cast */
}

#define JSONTABLES_NAME "jsontables"

#line 54 "../json/json.l"


